name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the build environment (e.g., install dependencies)
      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format-15 valgrind libcunit1 libcunit1-doc libcunit1-dev

      # Step 3: Navigate to the project directory and build the project
      - name: Build project
        working-directory: advent-of-code-2024
        run: make all

      # Step 4: Run the unit tests
      - name: Run unit tests
        working-directory: advent-of-code-2024
        run: make test

      # Step 5: Check for memory leaks using Valgrind (optional)
      - name: Run tests with Valgrind
        working-directory: advent-of-code-2024
        run: make valgrind
